package com.manhnk.app.model;
// Generated Apr 19, 2020 7:59:47 AM by Hibernate Tools 5.2.12.Final


import java.util.Date;

/**
 * Auth generated by hbm2java
 */
public class Auth implements java.io.Serializable {


  private Long id;
  private Menu menu;
  private Role role;
  private int permission;
  private int activeFlag;
  private Date createdDate;
  private Date updateDate;

  public Auth() {}

  public Auth(Menu menu, Role role, int permission, int activeFlag, Date createdDate,
      Date updateDate) {
    this.menu = menu;
    this.role = role;
    this.permission = permission;
    this.activeFlag = activeFlag;
    this.createdDate = createdDate;
    this.updateDate = updateDate;
  }

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Menu getMenu() {
    return this.menu;
  }

  public void setMenu(Menu menu) {
    this.menu = menu;
  }

  public Role getRole() {
    return this.role;
  }

  public void setRole(Role role) {
    this.role = role;
  }

  public int getPermission() {
    return this.permission;
  }

  public void setPermission(int permission) {
    this.permission = permission;
  }

  public int getActiveFlag() {
    return this.activeFlag;
  }

  public void setActiveFlag(int activeFlag) {
    this.activeFlag = activeFlag;
  }

  public Date getCreatedDate() {
    return this.createdDate;
  }

  public void setCreatedDate(Date createdDate) {
    this.createdDate = createdDate;
  }

  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


