package com.manhnk.app.model;
// Generated Apr 19, 2020 7:59:47 AM by Hibernate Tools 5.2.12.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {


  private long id;
  private String name;
  private String code;
  private String description;
  private int activeFlag;
  private Date createdDate;
  private Date updateDate;
  private Set productInfos = new HashSet(0);

  public Category() {}


  public Category(long id, String name, String code, int activeFlag, Date createdDate,
      Date updateDate) {
    this.id = id;
    this.name = name;
    this.code = code;
    this.activeFlag = activeFlag;
    this.createdDate = createdDate;
    this.updateDate = updateDate;
  }

  public Category(long id, String name, String code, String description, int activeFlag,
      Date createdDate, Date updateDate, Set productInfos) {
    this.id = id;
    this.name = name;
    this.code = code;
    this.description = description;
    this.activeFlag = activeFlag;
    this.createdDate = createdDate;
    this.updateDate = updateDate;
    this.productInfos = productInfos;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getCode() {
    return this.code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public int getActiveFlag() {
    return this.activeFlag;
  }

  public void setActiveFlag(int activeFlag) {
    this.activeFlag = activeFlag;
  }

  public Date getCreatedDate() {
    return this.createdDate;
  }

  public void setCreatedDate(Date createdDate) {
    this.createdDate = createdDate;
  }

  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }

  public Set getProductInfos() {
    return this.productInfos;
  }

  public void setProductInfos(Set productInfos) {
    this.productInfos = productInfos;
  }



}


