package com.manhnk.app.model;
// Generated Apr 19, 2020 7:59:47 AM by Hibernate Tools 5.2.12.Final


import java.math.BigDecimal;
import java.util.Date;

/**
 * History generated by hbm2java
 */
public class History implements java.io.Serializable {


  private Long id;
  private ProductInfo productInfo;
  private String actionName;
  private int type;
  private int quantity;
  private BigDecimal price;
  private int activeFlag;
  private Date createdDate;
  private Date updateDate;

  public History() {}

  public History(ProductInfo productInfo, String actionName, int type, int quantity,
      BigDecimal price, int activeFlag, Date createdDate, Date updateDate) {
    this.productInfo = productInfo;
    this.actionName = actionName;
    this.type = type;
    this.quantity = quantity;
    this.price = price;
    this.activeFlag = activeFlag;
    this.createdDate = createdDate;
    this.updateDate = updateDate;
  }

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ProductInfo getProductInfo() {
    return this.productInfo;
  }

  public void setProductInfo(ProductInfo productInfo) {
    this.productInfo = productInfo;
  }

  public String getActionName() {
    return this.actionName;
  }

  public void setActionName(String actionName) {
    this.actionName = actionName;
  }

  public int getType() {
    return this.type;
  }

  public void setType(int type) {
    this.type = type;
  }

  public int getQuantity() {
    return this.quantity;
  }

  public void setQuantity(int quantity) {
    this.quantity = quantity;
  }

  public BigDecimal getPrice() {
    return this.price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public int getActiveFlag() {
    return this.activeFlag;
  }

  public void setActiveFlag(int activeFlag) {
    this.activeFlag = activeFlag;
  }

  public Date getCreatedDate() {
    return this.createdDate;
  }

  public void setCreatedDate(Date createdDate) {
    this.createdDate = createdDate;
  }

  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


