package com.manhnk.app.model;
// Generated Apr 19, 2020 7:59:47 AM by Hibernate Tools 5.2.12.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {


  private long id;
  private String roleName;
  private String description;
  private int activeFlag;
  private Date createdDate;
  private Date updateDate;
  private Set auths = new HashSet(0);
  private Set userRoles = new HashSet(0);

  public Role() {}


  public Role(long id, String roleName, String description, int activeFlag, Date createdDate,
      Date updateDate) {
    this.id = id;
    this.roleName = roleName;
    this.description = description;
    this.activeFlag = activeFlag;
    this.createdDate = createdDate;
    this.updateDate = updateDate;
  }

  public Role(long id, String roleName, String description, int activeFlag, Date createdDate,
      Date updateDate, Set auths, Set userRoles) {
    this.id = id;
    this.roleName = roleName;
    this.description = description;
    this.activeFlag = activeFlag;
    this.createdDate = createdDate;
    this.updateDate = updateDate;
    this.auths = auths;
    this.userRoles = userRoles;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getRoleName() {
    return this.roleName;
  }

  public void setRoleName(String roleName) {
    this.roleName = roleName;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public int getActiveFlag() {
    return this.activeFlag;
  }

  public void setActiveFlag(int activeFlag) {
    this.activeFlag = activeFlag;
  }

  public Date getCreatedDate() {
    return this.createdDate;
  }

  public void setCreatedDate(Date createdDate) {
    this.createdDate = createdDate;
  }

  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }

  public Set getAuths() {
    return this.auths;
  }

  public void setAuths(Set auths) {
    this.auths = auths;
  }

  public Set getUserRoles() {
    return this.userRoles;
  }

  public void setUserRoles(Set userRoles) {
    this.userRoles = userRoles;
  }



}


