package com.manhnk.app.model;
// Generated Apr 19, 2020 7:59:47 AM by Hibernate Tools 5.2.12.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {


  private long id;
  private String userName;
  private String password;
  private String email;
  private String name;
  private int activeFlag;
  private Date createdDate;
  private Date updateDate;
  private Set userRoles = new HashSet(0);

  public User() {}


  public User(long id, String userName, String password, String email, String name, int activeFlag,
      Date createdDate, Date updateDate) {
    this.id = id;
    this.userName = userName;
    this.password = password;
    this.email = email;
    this.name = name;
    this.activeFlag = activeFlag;
    this.createdDate = createdDate;
    this.updateDate = updateDate;
  }

  public User(long id, String userName, String password, String email, String name, int activeFlag,
      Date createdDate, Date updateDate, Set userRoles) {
    this.id = id;
    this.userName = userName;
    this.password = password;
    this.email = email;
    this.name = name;
    this.activeFlag = activeFlag;
    this.createdDate = createdDate;
    this.updateDate = updateDate;
    this.userRoles = userRoles;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getUserName() {
    return this.userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public String getPassword() {
    return this.password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public String getEmail() {
    return this.email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public int getActiveFlag() {
    return this.activeFlag;
  }

  public void setActiveFlag(int activeFlag) {
    this.activeFlag = activeFlag;
  }

  public Date getCreatedDate() {
    return this.createdDate;
  }

  public void setCreatedDate(Date createdDate) {
    this.createdDate = createdDate;
  }

  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }

  public Set getUserRoles() {
    return this.userRoles;
  }

  public void setUserRoles(Set userRoles) {
    this.userRoles = userRoles;
  }



}


